# Generated by Django 4.2.26 on 2025-11-14 13:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('symbol_position', models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='before', max_length=10)),
                ('thousands_separator', models.CharField(default=',', max_length=1)),
                ('decimal_separator', models.CharField(default='.', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('result', models.DecimalField(decimal_places=6, max_digits=20)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('expiration_time', models.DateTimeField()),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_source', to='fx.currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_target', to='fx.currency')),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.DecimalField(decimal_places=6, max_digits=20)),
                ('buying', models.DecimalField(decimal_places=6, max_digits=20)),
                ('selling', models.DecimalField(decimal_places=6, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_as_source', to='fx.currency')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_as_target', to='fx.currency')),
            ],
            options={
                'ordering': ['source', 'target'],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
